name: Build for macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SFML
        run: brew install sfml

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir dist
          cp build/MultiGame dist/
          cd dist && zip -r MultiGame-macos.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MultiGame-macos
          path: dist/MultiGame-macos.zip